version: '3.8'

services:
  web:
    build: .
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - MONGO_URI
      - DATABASE_NAME
      - RABBITMQ_URI
    depends_on:
      - rabbitmq
      - mongo

  workers:
    build: .
    restart: on-failure
    environment:
      - MONGO_URI
      - DATABASE_NAME
      - RABBITMQ_URI
    entrypoint: ./entrypoint_workers.sh
    depends_on:
      - rabbitmq
      - mongo

  rabbitmq:
    image: rabbitmq:latest
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  mongo:
    image: mongo:latest